import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#464555",
        "surface-container-high": "#2a2933",
        "primary": "#c3c0ff",
        "primary-container": "#4f46e5",
        "on-primary": "#1d00a5",
        "on-primary-container": "#dad7ff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-low": "#1b1b24",
        "background": "#13121b",
        "on-tertiary-fixed": "#23005c",
        "tertiary-fixed": "#e9ddff",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "inverse-primary": "#4d44e3",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-container-highest": "#35343e",
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#6f3dd9",
        "surface-dim": "#13121b",
        "surface-container": "#1f1f28",
        "secondary-container": "#00a572",
        "inverse-surface": "#e4e1ee",
        "inverse-on-surface": "#302f39",
        "surface-container-lowest": "#0e0d16",
        "surface-tint": "#c3c0ff",
        "on-primary-fixed-variant": "#3323cc",
        "secondary": "#4edea3",
        "outline": "#918fa1",
        "error": "#ffb4ab",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-container": "#e3d5ff",
        "error-container": "#93000a",
        "surface-variant": "#35343e",
        "on-secondary-container": "#00311f",
        "surface": "#13121b",
        "surface-bright": "#393842",
        "on-surface": "#e4e1ee",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary": "#3c0091",
        "on-secondary-fixed": "#002113",
        "on-background": "#e4e1ee",
        "on-surface-variant": "#c7c4d8",
        "on-secondary": "#003824",
        "tertiary": "#d0bcff",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "80px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        base: "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-inter)"],
        display: ["var(--font-inter)"],
      },
      fontSize: {
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
