import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fcf8ff",
        "surface-dim": "#dcd8e5",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "surface-container": "#f0ecf9",
        "surface-container-high": "#eae6f4",
        "surface-container-highest": "#e4e1ee",
        "on-surface": "#1b1b24",
        "on-surface-variant": "#464555",
        "inverse-surface": "#302f39",
        "inverse-on-surface": "#f3effc",
        outline: "#777587",
        "outline-variant": "#c7c4d8",
        "surface-tint": "#4d44e3",
        primary: "#3525cd",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#c3c0ff",
        secondary: "#00687a",
        "on-secondary": "#ffffff",
        "secondary-container": "#57dffe",
        "on-secondary-container": "#006172",
        tertiary: "#7e3000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a44100",
        "on-tertiary-container": "#ffd2be",
        error: "#F43F5E",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        success: "#10B981",
        warning: "#F59E0B",
        "light-bg": "#F8FAFC",
        "light-surface": "#FFFFFF",
        "light-border": "#E5E7EB",
        "light-text-primary": "#0F172A",
        "light-text-secondary": "#64748B",
        "dark-bg": "#0B1120",
        "dark-surface": "#111827",
        "dark-card": "#1E293B",
        "dark-border": "#334155",
        "dark-text-primary": "#F8FAFC",
        "dark-text-secondary": "#CBD5E1",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        "container-max": "1440px",
        "content-max": "1280px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        small: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h4: ["20px", { lineHeight: "1.5", fontWeight: "500" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "hero-title": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
