import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3323cc",
        "surface": "#fcf8ff",
        "primary-container": "#4f46e5",
        "light-text-primary": "#0F172A",
        "dark-text-primary": "#F8FAFC",
        "surface-container-low": "#f5f2ff",
        "inverse-surface": "#302f39",
        "on-secondary-container": "#006172",
        "on-primary-container": "#dad7ff",
        "secondary-container": "#57dffe",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary-fixed-dim": "#ffb695",
        "error-container": "#ffdad6",
        "surface-dim": "#dcd8e5",
        "dark-text-secondary": "#CBD5E1",
        "surface-bright": "#fcf8ff",
        "secondary-fixed": "#acedff",
        "background": "#fcf8ff",
        "surface-container-highest": "#e4e1ee",
        "outline": "#777587",
        "inverse-primary": "#c3c0ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3effc",
        "warning": "#F59E0B",
        "tertiary-container": "#a44100",
        "dark-card": "#1E293B",
        "surface-tint": "#4d44e3",
        "error": "#F43F5E",
        "dark-border": "#334155",
        "on-primary": "#ffffff",
        "on-surface": "#1b1b24",
        "dark-surface": "#111827",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#351000",
        "light-surface": "#FFFFFF",
        "success": "#10B981",
        "on-secondary": "#ffffff",
        "surface-container": "#f0ecf9",
        "on-error-container": "#93000a",
        "light-bg": "#F8FAFC",
        "light-text-secondary": "#64748B",
        "tertiary": "#7e3000",
        "on-background": "#1b1b24",
        "dark-bg": "#0B1120",
        "surface-variant": "#e4e1ee",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed": "#001f26",
        "secondary": "#00687a",
        "on-primary-fixed": "#0f0069",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed-variant": "#7b2f00",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-container": "#ffd2be",
        "primary-fixed": "#e2dfff",
        "primary": "#3525cd",
        "light-border": "#E5E7EB",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-high": "#eae6f4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "3xl": "64px",
        "xs": "4px",
        "sm": "8px",
        "container-max": "1440px",
        "md": "16px",
        "base": "8px",
        "content-max": "1280px",
        "xl": "32px",
        "2xl": "48px",
        "lg": "24px",
        "gutter": "24px",
        "section-gap": "80px",
        "margin-mobile": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "caption": ["Inter"],
        "body": ["Inter"],
        "h1": ["Inter"],
        "h3": ["Inter"],
        "h2": ["Inter"],
        "small": ["Inter"],
        "hero-title": ["Inter"],
        "h4": ["Inter"],
        "display-xl": ["Inter"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "headline-lg": ["Inter"],
        "body-base": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "caption": ["12px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h1": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "small": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "hero-title": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "h4": ["20px", {"lineHeight": "1.5", "fontWeight": "500"}],
        "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-bold": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-base": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    }
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
